services:

      Twc\MakerBundle\ContextGenerator:
        arguments:
          - ''

      Twc\MakerBundle\Command\MakeTwcController:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
          - '@maker.file_manager'
        tags:
          - { name: 'maker.command'}

      Twc\MakerBundle\Command\MakeTwcValidator:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:validator' }

      Twc\MakerBundle\Command\MakeTwcForm:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:form' }

      Twc\MakerBundle\Command\MakeTwcMessage:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:message' }

      Twc\MakerBundle\Command\MakeTwcMessengerMiddleware:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:messenger-middleware' }

      Twc\MakerBundle\Command\MakeTwcVoter:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:voter' }

      Twc\MakerBundle\Command\MakeTwcCommand:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:command' }

      Twc\MakerBundle\Command\MakeTwcFixtures:
        arguments:
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'console.command', command: 'make:twc:fixtures' }

      Twc\MakerBundle\Command\MakeTwcEntity:
        arguments:
          - '@maker.file_manager'
          - '@maker.doctrine_helper'
          - '%kernel.project_dir%'
          - '@maker.generator'
          - '@Twc\MakerBundle\ContextGenerator'
        tags:
          - { name: 'maker.command'}